### ISSUE TITLE
drawString draws a preceding line before x pos?

### ISSUE THREAD

**Issue by gslender** [freetronics/FTOLED#6]
Not sure why, but the code for drawString has these lines... which draw a line before the chars... not sure why and only makes it annoying because the bounding box isn't just X,Y, X + width, Y + height.... it is X-1,Y, X + width+1, Y + height.... ??????

```
  if(x >= 0)
    oled->drawLine(x-1 , y, x-1 , y + header.height - 1, background);
```

**Comment by projectgus** [comment]
Hi Grant,

Sorry for the slow reply.

The reason for the lines after the first character is to erase any space between letters, because otherwise the old characters end up there.

We shouldn't do it before the first character though, I think that's a bug.

**Comment by projectgus** [comment]
Thanks again for reporting this.

I've fixed that bug, and a couple of other bugs where background drawing seemed to be incorrect/ugly. Would appreciate any feedback if you still see pixels that are in the wrong place.

Angus
